server:
  port: 8989

spring:
  application:
    name: spring-admin
  cloud:
    discovery:
      client:
        simple:
          instances:
            service:
              - uri: http://localhost:9090
                metadata:
                  management.context-path: /actuator
              - uri: http://localhost:9091
                metadata:
                  management.context-path: /actuator
